import { useState, useEffect } from "react"
import { getDynamicInventoryRisk } from "@/lib/api"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { AlertTriangle, CheckCircle2, Package, RefreshCw, ShoppingCart } from "lucide-react"

export function HelpCenter() {
  return (
    <div className="max-w-4xl mx-auto py-8 text-left">
      <h2 className="text-3xl font-bold tracking-tight mb-2">Help Center</h2>
      <p className="text-muted-foreground mb-6">Need help with SalesOptima? Browse our guides or contact support.</p>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="hover:border-primary/40 transition-colors">
          <CardHeader>
            <CardTitle className="text-lg">Forecasting Guide</CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground leading-relaxed">
            Learn how the Prophet and tree-based autoregressive models parse your dataset, extract seasonality, and project demand.
          </CardContent>
        </Card>
        <Card className="hover:border-primary/40 transition-colors">
          <CardHeader>
            <CardTitle className="text-lg">Inventory Optimization</CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground leading-relaxed">
            Understand how safety stock and reorder point thresholds are calculated from average daily demand and forecast lead times.
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

export function Settings() {
  return (
    <div className="max-w-4xl mx-auto py-8 text-left">
      <h2 className="text-3xl font-bold tracking-tight mb-2">Application Settings</h2>
      <p className="text-muted-foreground mb-6">Manage system settings, integrations, and ML training schedules.</p>
      <Card className="border-muted/50">
        <CardHeader>
          <CardTitle className="text-lg">General Settings</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex justify-between items-center py-2.5 border-b">
            <div>
              <span className="font-semibold block text-sm">Theme Mode</span>
              <span className="text-xs text-muted-foreground">Adjust visual display settings.</span>
            </div>
            <Badge variant="outline">System Default</Badge>
          </div>
          <div className="flex justify-between items-center py-2.5 border-b">
            <div>
              <span className="font-semibold block text-sm">Database Sync</span>
              <span className="text-xs text-muted-foreground">Active PostgreSQL connection status.</span>
            </div>
            <Badge className="bg-green-500/10 text-green-500 hover:bg-green-500/10">Connected</Badge>
          </div>
          <div className="flex justify-between items-center py-2.5">
            <div>
              <span className="font-semibold block text-sm">Celery Background Workers</span>
              <span className="text-xs text-muted-foreground">Status of background worker loops.</span>
            </div>
            <Badge variant="secondary">Idle</Badge>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

export function Inventory() {
  const [items, setItems] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [reordered, setReordered] = useState<Record<string, boolean>>({})

  useEffect(() => {
    getDynamicInventoryRisk()
      .then(res => {
        setItems(res.data)
        setLoading(false)
      })
      .catch(err => {
        console.error(err)
        setLoading(false)
      })
  }, [])

  const handleReorder = (sku: string, qty: number) => {
    setReordered(prev => ({ ...prev, [sku]: true }))
    // Mock triggering a order placement activity
    setTimeout(() => {
      alert(`Purchase order dispatched: Requesting ${qty} units of SKU ${sku}`)
    }, 100)
  }

  // Stock overview summaries
  const criticalCount = items.filter(i => i.risk_level === 'Critical').length
  const mediumCount = items.filter(i => i.risk_level === 'Medium').length
  const healthyCount = items.filter(i => i.risk_level === 'Healthy').length

  return (
    <div className="space-y-6 text-left">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-primary to-emerald-600 bg-clip-text text-transparent">Inventory Optimization</h2>
          <p className="text-muted-foreground mt-2">Monitor real-time stock levels vs dynamic reorder targets generated by AI demand projections.</p>
        </div>
        <Button variant="outline" size="sm" onClick={() => {
          setLoading(true)
          getDynamicInventoryRisk().then(res => {
            setItems(res.data)
            setLoading(false)
          })
        }}>
          <RefreshCw className="w-4 h-4 mr-2" />
          Refresh Status
        </Button>
      </div>

      {/* Stock Cards Overview */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="border-red-500/20 bg-gradient-to-br from-red-500/5 to-transparent">
          <CardHeader className="pb-2">
            <CardDescription className="font-semibold text-red-500 uppercase tracking-wider text-xs">Critical Shortages</CardDescription>
            <CardTitle className="text-3xl font-bold flex justify-between items-center">
              {criticalCount} SKUs
              <AlertTriangle className="w-6 h-6 text-red-500" />
            </CardTitle>
          </CardHeader>
        </Card>
        <Card className="border-yellow-500/20 bg-gradient-to-br from-yellow-500/5 to-transparent">
          <CardHeader className="pb-2">
            <CardDescription className="font-semibold text-yellow-600 uppercase tracking-wider text-xs">Reorder Attention</CardDescription>
            <CardTitle className="text-3xl font-bold flex justify-between items-center">
              {mediumCount} SKUs
              <AlertTriangle className="w-6 h-6 text-yellow-500" />
            </CardTitle>
          </CardHeader>
        </Card>
        <Card className="border-emerald-500/20 bg-gradient-to-br from-emerald-500/5 to-transparent">
          <CardHeader className="pb-2">
            <CardDescription className="font-semibold text-emerald-600 uppercase tracking-wider text-xs">Healthy Supply</CardDescription>
            <CardTitle className="text-3xl font-bold flex justify-between items-center">
              {healthyCount} SKUs
              <CheckCircle2 className="w-6 h-6 text-emerald-500" />
            </CardTitle>
          </CardHeader>
        </Card>
      </div>

      <Card className="shadow-lg border-muted/50">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <Package className="w-5 h-5 text-primary" />
            Real-time Inventory Grid
          </CardTitle>
          <CardDescription>dynamic reorder calculations using 7-day lead times and forecast standard deviations</CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="text-sm text-muted-foreground text-center py-12">Loading stock grid...</div>
          ) : items.length === 0 ? (
            <div className="text-sm text-muted-foreground text-center py-12">No inventory data loaded. Generate forecast first to set parameters.</div>
          ) : (
            <div className="overflow-x-auto border rounded-lg">
              <table className="w-full border-collapse">
                <thead className="bg-muted/80">
                  <tr>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">SKU</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Product Name</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Current Stock</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Safety Stock</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Reorder Point</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">30D Projected Demand</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Supply Risk</th>
                    <th className="px-4 py-3 text-xs font-semibold text-muted-foreground border-b text-left uppercase">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((item, idx) => {
                    const badgeVariant = item.risk_level === 'Critical' ? 'destructive' : item.risk_level === 'Medium' ? 'secondary' : 'default'
                    return (
                      <tr key={idx} className="hover:bg-muted/20 transition-colors">
                        <td className="px-4 py-3 text-sm font-semibold border-b text-left">{item.sku}</td>
                        <td className="px-4 py-3 text-sm font-medium border-b text-left">{item.product_name}</td>
                        <td className="px-4 py-3 text-sm border-b text-left">{item.current_stock}</td>
                        <td className="px-4 py-3 text-sm border-b text-left">{item.safety_stock}</td>
                        <td className="px-4 py-3 text-sm border-b text-left">{item.reorder_point}</td>
                        <td className="px-4 py-3 text-sm border-b text-left">{item.forecast_demand.toFixed(0)} units</td>
                        <td className="px-4 py-3 text-sm border-b text-left">
                          <Badge variant={badgeVariant}>
                            {item.risk_level}
                          </Badge>
                        </td>
                        <td className="px-4 py-3 text-sm border-b text-left">
                          {item.risk_level !== 'Healthy' ? (
                            <Button 
                              size="sm" 
                              variant={reordered[item.sku] ? "secondary" : "default"}
                              disabled={reordered[item.sku]}
                              onClick={() => handleReorder(item.sku, item.reorder_quantity)}
                              className="flex items-center gap-1.5 h-8"
                            >
                              <ShoppingCart className="w-3.5 h-3.5" />
                              {reordered[item.sku] ? "Ordered" : `Order ${item.reorder_quantity}`}
                            </Button>
                          ) : (
                            <span className="text-xs text-muted-foreground font-semibold">Stock Adequate</span>
                          )}
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
